### ISSUE TITLE
rendering r code

### ISSUE THREAD

**Issue by FelicienLL** [nlmixr2/blog#16]
Hi, this chunk is not rendered in the blog post, I think `{}` are missing. :( 
Best regards

Félicien

https://github.com/nlmixr2/blog/blob/0cf4a9d54777202dde313fba357bcdbe8d1da950/content/blog/2022-10-25-nlmixr-objf/index.Rmd#L243

**Comment by mattfidler** [comment]
Thanks @FelicienLL 

Completed
